import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ApplicationCommandType } from "discord-api-types/v10";
import { optionsAt } from "../commands/options.js";
import type { RouteGraph } from "../compiler/graph.js";
import { type NectarPlugin, PluginError, pluginGraph } from "../plugins/index.js";

export const TYPES_FILE = "types.d.ts";

const PACKAGE = "@nectar-js/nectar";

const COMMAND_TYPE: Record<number, string> = {
  [ApplicationCommandType.ChatInput]: "chatInput",
  [ApplicationCommandType.User]: "user",
  [ApplicationCommandType.Message]: "message",
};

/**
 * Renders `types.d.ts`: a module augmentation of `@nectar-js/nectar` that lists every route with
 * its parameters and options. Whatever a plugin's `types` hook returns is appended after it.
 */
export function toTypes(graph: RouteGraph, plugins: readonly NectarPlugin[] = []): string {
  const commands: string[] = [];
  for (const command of [...graph.commands].sort((a, b) => a.name.localeCompare(b.name))) {
    for (const [key, route] of Object.entries(command.handlers)) {
      const options = optionsAt(command.payload, key)
        .map((o) => `${quote(o.name)}: { type: ${quote(o.type)}; required: ${o.required} }`)
        .join("; ");
      commands.push(
        `    ${quote(route.path)}: { type: ${quote(COMMAND_TYPE[command.type] ?? "chatInput")}; options: {${options === "" ? "" : ` ${options} `}} };`,
      );
    }
  }
  commands.sort();

  // The compiler allows one handler per component path, so each path has one kind.
  const components = [...graph.components]
    .sort((a, b) => a.path.localeCompare(b.path))
    .map((route) => {
      const params = route.params
        .map((name) => `${quote(name)}: ${name === route.catchAll ? "string[]" : "string"}`)
        .join("; ");
      const kind = route.kind === "select" ? `select:${route.selectKind}` : route.kind;
      return `    ${quote(route.path)}: { kind: ${quote(kind)}; params: {${params === "" ? "" : ` ${params} `}} };`;
    });

  const events = graph.events.map((e) => `    ${quote(e.name)}: true;`);
  const autocomplete = graph.autocomplete
    .map((a) => `    ${quote(a.route.path)}: ${a.options.map(quote).join(" | ") || "never"};`)
    .sort();

  return [
    "// Generated by Nectar. Do not edit.",
    "",
    `declare module ${quote(PACKAGE)} {`,
    "  interface NectarRoutes {",
    "    commands: {",
    ...commands.map(indent),
    "    };",
    "    components: {",
    ...components.map(indent),
    "    };",
    "    events: {",
    ...events.map(indent),
    "    };",
    "    autocomplete: {",
    ...autocomplete.map(indent),
    "    };",
    "  }",
    "}",
    "",
    "export {};",
    "",
    ...pluginTypes(graph, plugins),
  ].join("\n");
}

function pluginTypes(graph: RouteGraph, plugins: readonly NectarPlugin[]): string[] {
  const lines: string[] = [];
  for (const plugin of plugins) {
    if (plugin.types === undefined) continue;
    let extra: unknown;
    try {
      extra = plugin.types(pluginGraph(graph));
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new PluginError(plugin.name, `types failed: ${detail}`);
    }
    if (typeof extra !== "string" || extra.trim() === "") continue;
    lines.push(`// From plugin ${JSON.stringify(plugin.name)}`, extra.trim(), "");
  }
  return lines;
}

export function writeTypes(
  graph: RouteGraph,
  outDir: string,
  plugins: readonly NectarPlugin[] = [],
): string {
  mkdirSync(outDir, { recursive: true });
  const file = path.join(outDir, TYPES_FILE);
  writeFileSync(file, toTypes(graph, plugins));
  return file;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function indent(line: string): string {
  return `  ${line}`;
}
