import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { ApplicationCommandOptionType, ApplicationCommandType } from "discord-api-types/v10";
import type { RouteGraph } from "../compiler/graph.js";
import type { Route } from "../compiler/routes.js";
import type { ComponentRoute } from "../components/compile.js";

export const TYPES_FILE = "types.d.ts";

const PACKAGE = "@neatjs/core";

const COMMAND_TYPE: Record<number, string> = {
  [ApplicationCommandType.ChatInput]: "chatInput",
  [ApplicationCommandType.User]: "user",
  [ApplicationCommandType.Message]: "message",
};

const OPTION_TYPE: Record<number, string> = {
  [ApplicationCommandOptionType.String]: "string",
  [ApplicationCommandOptionType.Integer]: "integer",
  [ApplicationCommandOptionType.Number]: "number",
  [ApplicationCommandOptionType.Boolean]: "boolean",
  [ApplicationCommandOptionType.User]: "user",
  [ApplicationCommandOptionType.Channel]: "channel",
  [ApplicationCommandOptionType.Role]: "role",
  [ApplicationCommandOptionType.Mentionable]: "mentionable",
  [ApplicationCommandOptionType.Attachment]: "attachment",
};

/**
 * Renders `types.d.ts`: a module augmentation of `@neatjs/core` that lists every route with
 * its parameters, options, and the context its middleware chain adds. Handler and middleware
 * types are pulled in with `import()` type queries relative to `outDir`.
 */
export function toTypes(graph: RouteGraph, outDir: string): string {
  const absoluteOut = path.resolve(outDir);
  const middlewareAliases = new Map<string, string>();
  const aliasFor = (file: string): string => {
    let alias = middlewareAliases.get(file);
    if (alias === undefined) {
      alias = `M${middlewareAliases.size}`;
      middlewareAliases.set(file, alias);
    }
    return alias;
  };
  const contextOf = (route: Route): string => {
    const files = graph.chains.get(route.file)?.middleware ?? [];
    return files.length === 0 ? "{}" : files.map(aliasFor).join(" & ");
  };

  const commands: string[] = [];
  for (const command of [...graph.commands].sort((a, b) => a.name.localeCompare(b.name))) {
    for (const [key, route] of Object.entries(command.handlers)) {
      const options = Object.entries(optionsAt(command.payload, key))
        .map(([name, type]) => `${quote(name)}: ${quote(type)}`)
        .join("; ");
      commands.push(
        `    ${quote(route.path)}: { type: ${quote(COMMAND_TYPE[command.type] ?? "chatInput")}; options: {${options === "" ? "" : ` ${options} `}}; context: ${contextOf(route)} };`,
      );
    }
  }
  commands.sort();

  const byPath = new Map<string, { kinds: Set<string>; route: ComponentRoute }>();
  for (const route of graph.components) {
    const kind = route.kind === "select" ? `select:${route.selectKind}` : route.kind;
    const entry = byPath.get(route.path) ?? { kinds: new Set(), route };
    entry.kinds.add(kind);
    byPath.set(route.path, entry);
  }
  const components = [...byPath]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([routePath, { kinds, route }]) => {
      const params = route.params
        .map((name) => `${quote(name)}: ${name === route.catchAll ? "string[]" : "string"}`)
        .join("; ");
      const kind = [...kinds].sort().map(quote).join(" | ");
      return `    ${quote(routePath)}: { kind: ${kind}; params: {${params === "" ? "" : ` ${params} `}}; context: ${contextOf(route)} };`;
    });

  const events = graph.events.map((e) => `    ${quote(e.name)}: true;`);
  const autocomplete = graph.autocomplete
    .map((a) => `    ${quote(a.route.path)}: ${a.options.map(quote).join(" | ") || "never"};`)
    .sort();

  const aliases = [...middlewareAliases].map(
    ([file, alias]) =>
      `type ${alias} = MiddlewareExtension<typeof import(${quote(importPath(absoluteOut, file))})>;`,
  );

  return [
    "// Generated by Neat. Do not edit.",
    `import type { MiddlewareExtension } from ${quote(PACKAGE)};`,
    ...(aliases.length === 0 ? [] : ["", ...aliases]),
    "",
    `declare module ${quote(PACKAGE)} {`,
    "  interface NeatRoutes {",
    "    commands: {",
    ...commands.map(indent),
    "    };",
    "    components: {",
    ...components.map(indent),
    "    };",
    "    events: {",
    ...events.map(indent),
    "    };",
    "    autocomplete: {",
    ...autocomplete.map(indent),
    "    };",
    "  }",
    "}",
    "",
    "export {};",
    "",
  ].join("\n");
}

export function writeTypes(graph: RouteGraph, outDir: string): string {
  mkdirSync(outDir, { recursive: true });
  const file = path.join(outDir, TYPES_FILE);
  writeFileSync(file, toTypes(graph, outDir));
  return file;
}

interface PayloadNode {
  name?: string;
  type?: number;
  options?: PayloadNode[];
}

/** Option name to option type name for one handler position of a command payload. */
function optionsAt(payload: unknown, key: string): Record<string, string> {
  let options = (payload as PayloadNode).options;
  for (const part of key === "" ? [] : key.split("/")) {
    options = options?.find((o) => o.name === part)?.options;
  }
  const out: Record<string, string> = {};
  for (const option of options ?? []) {
    const type = option.type === undefined ? undefined : OPTION_TYPE[option.type];
    if (option.name !== undefined && type !== undefined) out[option.name] = type;
  }
  return out;
}

/** `../app/middleware.ts` becomes `../app/middleware.js`, which NodeNext resolves back to the source. */
function importPath(fromDir: string, file: string): string {
  const relative = path.relative(fromDir, file).split(path.sep).join("/");
  const mapped = relative.replace(/\.mts$/, ".mjs").replace(/\.ts$/, ".js");
  return mapped.startsWith(".") ? mapped : `./${mapped}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function indent(line: string): string {
  return `  ${line}`;
}
